spring:
  application:
    name: companies
  datasource:
    username: match
    password: service
    url: jdbc:postgresql://localhost:5432/match
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true