server:
  port: 8090

spring:
  application:
    name: companies
  datasource:
    username: smatch
    password: servicematch
    url: jdbc:postgresql://localhost:5440/companiesms
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
#  cloud:
#    config:
#      enabled: false
#    bus:
#      enabled: false
  devtools:
    restart:
      enabled: true
      poll-interval: 5s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

#  shutdown:
#    enabled: true

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8070/eureka

info:
  app:
    name: "companies"