server:
  port: 8095

spring:
  application:
    name: users
  datasource:
    username: service_user
    password: service
    url: jdbc:postgresql://192.168.33.15:5434/service_users
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
#  cloud:
#    config:
#      enabled: false
#    bus:
#      enabled: false
  devtools:
    restart:
      enabled: true
      poll-interval: 5s
