services:
  projects:
    # image: mongo
    image: mongo:noble
    restart: always
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: smatch
    #   MONGO_INITDB_ROOT_PASSWORD: servicematch

  companies:
    image: postgres:alpine
    restart: always
    ports:
      - "5440:5432"
    env_file:
      - .env
    volumes:
      - ./data:/docker_entry.d
