spring:
  application:
    name: projects
  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: "service_match"
  cloud:
    config:
      enabled: false
    bus:
      enabled: false
